### ISSUE TITLE
JDK 11 Support

### ISSUE THREAD

**Issue by willcohen** [brandonbloom/fipp#50]
[core.rrb-vector's next release](https://dev.clojure.org/jira/browse/CRRBV-18) will include a fix for JDK 11 compatibility, at which point fipp should be updated as well.

**Comment by tirkarthi** [comment]
Thanks @willcohen I was just testing it. The clojurescript dev profile dependency in project.clj should also be updated to `1.10.238` since the current version is incompatible with JDK 8 causing compilation errors. It will be also helpful to add Travis to catch these errors in future.

JDK 11 build failure due to core.rrb-vector : https://travis-ci.org/tirkarthi/fipp/jobs/402077194

**Comment by brandonbloom** [comment]
Assuming this is just a dependency upgrade, happy to make the change for the next release. Send a message when that time comes, since I'm not moving to JDK 11 myself immediately.

**Comment by middlesphere** [comment]
Java 11 is out! Please, upgrade this lib. Thanks.

**Comment by brandonbloom** [comment]
I'm not in a rush. Waiting on the rrb release. If this affects you, please send a pull request when rrb is updated.

**Comment by brandonbloom** [comment]
OK continuing discussion over at https://github.com/brandonbloom/fipp/pull/51

**Comment by brandonbloom** [comment]
Deployed 0.6.13

**Comment by phillipm** [comment]
Hello, would it be possible to bump to `rrb-vector` `0.0.13` to address some additional warnings?
We bumped `midje` to `fipp` `0.6.13` in https://github.com/marick/Midje/pull/447#issuecomment-430987730 and have since had to pin the latest version of `rrb-vector` to get rid of some warnings: https://github.com/marick/Midje/pull/448

Thanks!
